TUM-DSE/doctor-cluster-config

modules/swiss-knife/users.nix
=> swiss-knife: switch teams

README.md, home/.config/nixpkgs/home.nix
home.nix example and VS Code support documentation
=> home.nix example and VS Code support documentation

modules/students.nix
=> Update Paul's SSH key

hosts/christina.nix
Configure PM in AppDirect mode in Christina
=> add the dax module in christina

modules/students.nix
=> students: add Vanda

pkgs/xilinx/fhs-env.nix
=> Add libcrypt.so back to fhs

configurations.nix
otherwise wezterm user have no working backspace :(
=> Add wezterm terminfo

hosts/ryan.nix
=> ryan: mount nfs again

modules/users/students.nix
I hope there are no more mistakes...
=> completely delete sys-lab-#1 students

hosts/clara.nix
Enable dpdk in clara for @dgiantsidi 's experiments
=> Enable dpdk in clara for Dimitra's experiments

hosts/doctor.nix
=> doctor: set simd.arch

hosts/jack.nix, modules/llama.nix
=> add llama service

modules/vicuna.nix
=> vicuna: enable api

tasks.py
=> fix format

tasks.py
=> add ipmitool helper function

modules/nfs/server-backup.nix, modules/nfs/server.nix
=> setup nfs server ips after network target

hosts/ryan.nix, pkgs/kernels/linux-sev-snp.nix
This works on ryan.
This change will affect rose and we need to check if it's acceptable before merging.
=> sev-snp: update kernel to 6.3

configurations.nix, flake.lock, modules/apple-silicon-support/modules/boot-m1n1/default.nix, modules/apple-silicon-support/modules/kernel/default.nix, modules/apple-silicon-support/packages/overlay.nix
This should save evaluation time and memory
=> configurations.nix: set pkgs instead of system

modules/users/admins.nix, modules/users/chair-members.nix, modules/users/default.nix, modules/users/extra-user-options.nix, modules/users/students.nix
all students without "allowedHosts" need updating now. Add `allowedHosts = [ "all" ];` to allow all hosts
=> users: make allowed hosts "all" more explicit

modules/users/students.nix
- restrict `eaypek`'s access to `rose` and `ryan` 
- remove `mwerndle` user
=> Restrict student's access

hosts/vislor.nix
- also bump vislor stateversion
=> vislor: enable SEV

docs/README.md
- students can't use LRZ VPN to acess servers
- reflect this in docs by removing entry + highlighting jump
=> docs: update vpn docs

configurations.nix, flake.lock, flake.nix, modules/buildbot/master.nix, modules/nix-daemon.nix, modules/nvidia.nix, modules/users/admins.nix, modules/xilinx.nix, modules/xrdp-passwords.nix, pkgs/xilinx/xrt.nix
This reverts commit f2d8dc01354869c19dcf12ff369e4c06c64f05e0.
=> Upgrade to 23.11
